# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
env:
  - DOCUMENTER_DEBUG=true
notifications:
  email: false
script:
  - julia --project=. --color=yes -e 'using Pkg; Pkg.instantiate()'
  - travis_wait 40 julia --project=. --color=yes docs/make.jl
